os_type: linux
shell_type: bash

provisioner:
  name: shell
  data_path: ./
  command: pushd C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/data; . provision/init.sh

platforms:

  - name: docker-win2012
    os_type: linux
    shell_type: bash
    provisioner:
      root_path: "C:/Users/Administrator/AppData/Local/Temp/kitchen"
    transport:
      name: rsync_ssh
      username: Administrator
      password: setup
    driver_config:
      name: docker
      image: alpine
      dockerfile: ./Dockerfile
      privileged: true
      use_internal_docker_network: true
      public_key: "<%= ENV['HOME'] %>/.ssh/id_rsa.pub"
      private_key: "<%= ENV['HOME'] %>/.ssh/id_rsa"
      volume:
        - /opt/qemu:/opt/qemu
      run_command:
      username: Administrator

suites:
  - name: default

