os_type: linux
shell_type: bash

provisioner:
  name: shell
  data_path: ./provision
  command: ./provision/init.sh

driver:
  image: alpine
  name: docker
  dockerfile: ./Dockerfile
  privileged: true
  use_internal_docker_network: true
  public_key: "<%= ENV['HOME'] %>/.ssh/id_rsa.pub"
  private_key: "<%= ENV['HOME'] %>/.ssh/id_rsa"
  # build_context: 
  volume:
    - /opt/qemu:/opt/qemu
  run_command:

platforms:
  - name: win2012
    os_type: linux
    shell_type: bash
    provisioner:
      root_path: "C:/Users/Administrator/AppData/Local/Temp/kitchen"
    transport:
      name: ssh
      username: Administrator
      password: setup
    driver_config:
      username: Administrator

suites:
  - name: default

