language: shell

matrix:
  include:
  - name: "selenoid-bin-windows"
    env: HAB_PKG=selenoid-bin-latest
    os: windows
  - name: "selenoid-bin-linux"
    env: HAB_PKG=selenoid-bin-latest
    os: linux
  - name: "geckodriver-bin-windows"
    env: HAB_PKG=geckodriver-bin-latest
    os: windows

script:
  - bash ./travis/build.sh
