language: shell

matrix:
  include:
  - name: "selenoid-bin-windows"
    env: HAB_PKG=selenoid-bin
    os: windows
  - name: "selenoid-bin-linux"
    env: HAB_PKG=selenoid-bin
    os: linux
  - name: "arch-install-scripts"
    env: HAB_PKG=arch-install-scripts
    os: linux
  - name: "gitbook-cli"
    env: HAB_PKG=gitbook-cli
    os: linux

script:
  - bash ./travis/build.sh
