language: shell

matrix:
  include:
  - name: "selenoid-bin"
    env: HAB_PKG=selenoid-bin
    os:
      - windows
  - name: "arch-install-scripts"
    env: HAB_PKG=arch-install-scripts
    os:
      - linux
  - name: "gitbook-cli"
    env: HAB_PKG=gitbook-cli
    os:
      - linux

script:
  - bash ./travis/build.sh
