language: shell

matrix:
  include:
  - name: "selenoid-bin-windows"
    env: HAB_PKG=selenoid-bin
    os: windows
  - name: "selenoid-bin-linux"
    env: HAB_PKG=selenoid-bin-latest
    os: linux

script:
  - bash ./travis/build.sh
